local wow = require("wow")

describe("boot smoke", function()
    it("loads every TOC file and boots without errors", function()
        local state = wow.defaultState()
        wow.putItem(state, 0, 1, 6948, 1)
        wow.putItem(state, 0, 2, 2589, 20)
        local env, ns = wow.boot(state)
        assert.are.same({}, env.__errors)
        assert.is_true(ns.ready)
        local c = ns.db.chars["Alice-Blackhand"]
        assert.is_table(c)
        assert.are.equal("6948,1", c.bags[0].items[1])
        assert.are.equal("2589,20", c.bags[0].items[2])
    end)
end)

describe("mock client sanity", function()
    it("delivers each event exactly once per registered frame", function()
        local env = wow.newEnv(wow.defaultState())
        local f = env.CreateFrame("Frame")
        local n = 0
        f:RegisterEvent("A")
        f:RegisterEvent("B")
        f:RegisterEvent("A")
        f:SetScript("OnEvent", function(_, e) if e == "A" then n = n + 1 end end)
        env.FireEvent("A")
        assert.are.equal(1, n)
    end)
end)
