local ns = EllesmereUIBagsAlts._ns

simtest("bags are scanned from the real C_Container API", function()
    A_Admin.AddBagItem(0, 1, 2589, 20)
    A_Admin.AddBagItem(1, 3, 6948, 1)
    A_Admin.FireEvent("BAG_UPDATE", 0)
    A_Admin.FireEvent("BAG_UPDATE", 1)
    A_Admin.FireEvent("BAG_UPDATE_DELAYED")
    local c = ns.GetPlayerChar()
    assertNotNil(c)
    assertEquals("2589,20", c.bags[0].items[1])
    assertEquals("6948,1", c.bags[1].items[3])
    assertEquals(16, c.bags[0].size)
end)

simtest("character record has identity, class and money", function()
    local key = ns.GetPlayerKey()
    assertNotNil(key)
    local c = ns.GetPlayerChar()
    assertType("string", c.class)
    assertType("number", c.money)
    assertType("number", c.lastSeen)
end)

simtest("index and public API report the scanned stacks", function()
    local total, byOwner = EllesmereUIBagsAlts.GetItemCount(2589)
    assertEquals(20, total)
    assertEquals(20, byOwner[ns.GetPlayerKey()].bags)
end)

simtest("removing an item updates the store incrementally", function()
    A_Admin.RemoveBagItem(1, 3)
    A_Admin.FireEvent("BAG_UPDATE", 1)
    A_Admin.FireEvent("BAG_UPDATE_DELAYED")
    assertNil(ns.GetPlayerChar().bags[1].items[3])
    assertEquals(0, (EllesmereUIBagsAlts.GetItemCount(6948)))
end)

simtest("feature registry matches defaults (tooltip/header off, collectors on)", function()
    assertTrue(ns.IsFeatureActive("bags"))
    assertTrue(ns.IsFeatureActive("bank"))
    assertTrue(ns.IsFeatureActive("mail"))
    assertTrue(not ns.IsFeatureActive("tooltip"))
    assertTrue(not ns.IsFeatureActive("headerButton"))
    assertTrue(not ns.IsFeatureActive("guildbank"))
end)
