#!/usr/bin/env python3
"""API surface check: every WoW API the addon touches must exist in the
current client (Blizzard UI source, live branch, incl. generated API docs)
or in Ketho's vscode-wow-api annotations (C-level globals).

Checks
  * read_globals from .luacheckrc (addon section)
  * every C_Namespace.Function referenced in the addon source
  * every Enum.Type.Value referenced in the addon source
  * every event name passed to ns.RegisterEvent / RegisterEvent
  * every Blizzard template / frame type passed to CreateFrame
  * the EllesmereUI symbols the connector relies on (contract with EUI source)
Exit code 1 on any unknown symbol.
"""
import os
import re
import sys
import glob

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ADDON = os.path.join(ROOT, "EllesmereUIBags_Alts")
VENDOR = os.path.join(ROOT, ".tools", "vendor")
UI = os.path.join(VENDOR, "wow-ui-source", "Interface", "AddOns")
DOCS = os.path.join(UI, "Blizzard_APIDocumentationGenerated")
KETHO = os.path.join(VENDOR, "vscode-wow-api", "Annotations")
EUI = os.path.join(VENDOR, "EllesmereUI")

LUA_STD = set("""assert error ipairs next pairs pcall print rawequal rawget rawset select setmetatable
getmetatable tonumber tostring type unpack xpcall string table math os coroutine _G""".split())
# Not API functions: game data constants the client defines in C.
C_CONSTANTS = {"INVSLOT_FIRST_EQUIPPED", "INVSLOT_LAST_EQUIPPED"}
# GlobalStrings.lua is generated by the client (not part of wow-ui-source);
# these two have existed unchanged since the original client.
GLOBAL_STRINGS = {"CANCEL", "OKAY"}
EUI_SYMBOLS = {"EllesmereUI", "EUI_Bags", "EUI_CategoryManager", "EUI_CLIENT_BLOCKED"}


def read(path):
    with open(path, encoding="utf-8", errors="ignore") as fh:
        return fh.read()


def addon_sources():
    out = {}
    paths = glob.glob(os.path.join(ADDON, "**", "*.lua"), recursive=True)
    paths += glob.glob(os.path.join(ROOT, "upstream", "*.lua"))
    for path in paths:
        out[os.path.relpath(path, ROOT)] = read(path)
    return out


def load_docs():
    functions, enums, events, doc_globals = set(), {}, set(), set()
    for path in glob.glob(os.path.join(DOCS, "*.lua")):
        s = read(path)
        ns = re.search(r'Namespace = "([^"]+)"', s)
        ns = ns.group(1) if ns else None
        fsec = re.search(r"Functions =\s*\{(.*?)\n\t\},\n\n\tEvents", s, re.S)
        if fsec:
            for name in re.findall(r'\n\t\t\{\n\t\t\tName = "(\w+)",\n\t\t\tType = "Function"', fsec.group(1)):
                if ns:
                    functions.add(ns + "." + name)
                else:
                    doc_globals.add(name)
        for name in re.findall(r'LiteralName = "(\w+)"', s):
            events.add(name)
        for m in re.finditer(r'Name = "(\w+)",\n\t\t\tType = "Enumeration",.*?Fields =\s*\{(.*?)\n\t\t\t\},', s, re.S):
            enums.setdefault(m.group(1), set()).update(re.findall(r'\{ Name = "(\w+)"', m.group(2)))
    return functions, enums, events, doc_globals


def load_framexml_globals():
    names = set()
    for path in glob.glob(os.path.join(UI, "**", "*.lua"), recursive=True):
        if "APIDocumentation" in path:
            continue
        s = read(path)
        names.update(re.findall(r"^function ([A-Za-z_][\w]*)\s*\(", s, re.M))
        names.update(re.findall(r"^([A-Za-z_][\w]*)\s*=", s, re.M))
    xml_names = set()
    templates = set()
    for path in glob.glob(os.path.join(UI, "**", "*.xml"), recursive=True):
        s = read(path)
        names.update(re.findall(r"^\s*([A-Z][A-Z0-9_]+) = ", s, re.M))   # globals set in <Script> blocks
        for m in re.finditer(r'<(\w+)\s[^>]*?name="([\w$]+)"([^>]*)>', s):
            tag, name, rest = m.group(1), m.group(2), m.group(3)
            if "$" in name:
                continue
            if 'virtual="true"' in m.group(0) or 'intrinsic="true"' in m.group(0):
                templates.add(name)
            else:
                xml_names.add(name)
    return names, xml_names, templates


def load_ketho_globals():
    names = set()
    for path in glob.glob(os.path.join(KETHO, "**", "*.lua"), recursive=True):
        s = read(path)
        names.update(re.findall(r"^function ([A-Za-z_][\w]*)\s*\(", s, re.M))
        names.update(re.findall(r"^([A-Za-z_][\w]*)\s*=", s, re.M))
    return names


def luacheck_read_globals():
    s = read(os.path.join(ROOT, ".luacheckrc"))
    block = re.search(r'files\["EllesmereUIBags_Alts/\*\*/\*\.lua"\]\s*=\s*\{(.*?)\n\}', s, re.S).group(1)
    rg = re.search(r"read_globals\s*=\s*\{(.*?)\n    \}", block, re.S).group(1)
    rg = re.sub(r"--[^\n]*", "", rg)
    return re.findall(r'"(\w+)"', rg)


def main():
    functions, enums, events, doc_globals = load_docs()
    fx_globals, xml_names, templates = load_framexml_globals()
    ketho = load_ketho_globals()
    known_globals = fx_globals | xml_names | ketho | doc_globals | LUA_STD | C_CONSTANTS | GLOBAL_STRINGS
    sources = addon_sources()
    problems = []

    # 1. read globals
    for name in luacheck_read_globals():
        if name in EUI_SYMBOLS:
            continue
        if name.startswith("C_") or name in ("Enum", "Settings", "TooltipDataProcessor"):
            if name not in fx_globals and name not in ketho and not any(f.startswith(name + ".") for f in functions):
                problems.append("unknown namespace/global " + name)
            continue
        if name not in known_globals:
            problems.append("unknown global " + name)

    # 2. C_ functions, 3. Enum values, 4. events, 5. templates
    for rel, s in sources.items():
        for ns_name, fn in re.findall(r"\b(C_\w+)\.(\w+)\s*[\(,)]", s):
            full = ns_name + "." + fn
            if full not in functions:
                problems.append("%s: unknown function %s" % (rel, full))
        for enum_type, value in re.findall(r"\bEnum\.(\w+)\.(\w+)", s):
            if value not in enums.get(enum_type, ()):
                problems.append("%s: unknown enum Enum.%s.%s" % (rel, enum_type, value))
        for ev in re.findall(r'RegisterEvent\([^,]+,\s*"(\w+)"', s) + re.findall(r'RegisterEvent\("(\w+)"', s):
            if ev not in events:
                problems.append("%s: unknown event %s" % (rel, ev))
        for m in re.finditer(r'CreateFrame\("(\w+)"\s*,\s*[^,()]*(?:\([^)]*\))?[^,()]*,\s*[^,()]*,\s*"([\w, ]+)"', s):
            for tmpl in [t.strip() for t in m.group(2).split(",")]:
                if tmpl not in templates:
                    problems.append("%s: unknown template %s" % (rel, tmpl))
        for ftype in re.findall(r'CreateFrame\("(\w+)"', s):
            if ftype not in ("Frame", "Button", "EditBox", "ScrollFrame", "ItemButton", "StatusBar", "CheckButton"):
                problems.append("%s: unexpected frame type %s" % (rel, ftype))
        for method in re.findall(r"\bSettings\.(\w+)", s):
            if method not in ("VarType",) and not re.search(r"^function Settings\.%s\b" % method,
                                                            read(os.path.join(UI, "Blizzard_Settings_Shared", "Blizzard_Settings.lua")), re.M):
                problems.append("%s: unknown Settings.%s" % (rel, method))
        for method in re.findall(r"\bTooltipDataProcessor\.(\w+)", s):
            if method not in ("AddTooltipPostCall", "AddTooltipPreCall"):
                problems.append("%s: unknown TooltipDataProcessor.%s" % (rel, method))

    # 6. EllesmereUI contract
    eui_main = read(os.path.join(EUI, "EllesmereUI.lua"))
    eui_core = read(os.path.join(EUI, "EllesmereUI_UICore.lua"))
    eui_locale = read(os.path.join(EUI, "EllesmereUI_Locale.lua"))
    bags = read(os.path.join(EUI, "EllesmereUIBags", "EllesmereUIBags.lua"))
    cats = read(os.path.join(EUI, "EllesmereUIBags", "EllesmereUIBags_Categories.lua"))
    contract = [
        ("EllesmereUI.RegisterSkin", r"function EllesmereUI\.RegisterSkin\(name, applyFn\)", eui_main),
        ("EllesmereUI.GetFontPath", r"function EllesmereUI\.GetFontPath\(", eui_main),
        ("EllesmereUI.GetFontOutlineFlag", r"function EllesmereUI\.GetFontOutlineFlag\(", eui_main),
        ("EllesmereUI:ShowConfirmPopup(opts)", r"function EllesmereUI:ShowConfirmPopup\(opts\)", eui_main),
        ("EllesmereUI.ShowWidgetTooltip", r"EllesmereUI\.ShowWidgetTooltip = ShowWidgetTooltip", eui_core),
        ("EllesmereUI.HideWidgetTooltip", r"EllesmereUI\.HideWidgetTooltip = HideWidgetTooltip", eui_core),
        ("EllesmereUI.GetAccentColor", r"EllesmereUI\.GetAccentColor = function\(\)", eui_core),
        ("EllesmereUI.L", r"EllesmereUI\.L = L", eui_locale),
        ("_ModuleNS[EllesmereUIBags]", r'EllesmereUI\._ModuleNS\["EllesmereUIBags"\] = ns', bags),
        ("global EUI_Bags frame", r'^EUI_Bags = CreateFrame\("Frame", "EUI_MainBagFrame"', bags),
        ("EUI_Bags.Header", r"EUI_Bags\.Header = header", bags),
        ("header.itemCount", r"header\.itemCount = header:CreateFontString", bags),
        ("EUI_Bags._searchBox", r"EUI_Bags\._searchBox = search", bags),
        ("ns.SkinItemButton(btn, opts)", r"function ns\.SkinItemButton\(btn, opts\)", bags),
        ("ns.SetInsetBorderColor", r"ns\.SetInsetBorderColor = SetInsetBorderColor", bags),
        ("EUI_CategoryManager global", r"_G\.EUI_CategoryManager = CategoryManager", cats),
        ("CategoryManager:ClassifyItem(link, id, bag, slot)", r"function CategoryManager:ClassifyItem\(itemLink, itemID, bag, slot\)", cats),
        ("CategoryManager:GetCategories", r"function CategoryManager:GetCategories\(\)", cats),
    ]
    for label, pattern, text in contract:
        if not re.search(pattern, text, re.M):
            problems.append("EllesmereUI contract broken: " + label)

    # ASCII-only source (EUI house rule). Locale files are the documented
    # exception (CONTRIBUTING_TRANSLATIONS.md): UTF-8 without BOM, real
    # characters in the translated values, English (ASCII) keys.
    for rel, s in sources.items():
        is_locale = "/Locales/" in rel
        if is_locale:
            raw = open(os.path.join(ROOT, rel), "rb").read()
            if raw.startswith(b"\xef\xbb\xbf"):
                problems.append("%s: UTF-8 BOM" % rel)
            try:
                raw.decode("utf-8", errors="strict")
            except UnicodeDecodeError as exc:
                problems.append("%s: invalid UTF-8 (%s)" % (rel, exc))
        for lineno, line in enumerate(s.splitlines(), 1):
            if not any(ord(ch) > 127 for ch in line):
                continue
            if is_locale and re.match(r'^L\["[\x20-\x7e]*"\] = "', line):
                continue
            problems.append("%s:%d: non-ASCII character" % (rel, lineno))

    checked = len(luacheck_read_globals())
    if problems:
        print("API check FAILED (%d problems):" % len(problems))
        for p in sorted(set(problems)):
            print("  - " + p)
        return 1
    print("API check OK: %d globals, %d C_ functions/enums/events/templates scanned, EUI contract (%d symbols) intact"
          % (checked, len(functions), len(contract)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
