#!/usr/bin/env python3
"""Generates spec/fixtures/widget_methods.lua: the set of real widget (frame,
region, texture, font string, edit box, button, scroll frame, tooltip ...)
method names from Blizzard's generated API docs. The busted mock only accepts
these as unmodelled no-op methods, so a misspelled method name fails the tests
just like it would in the client."""
import glob, os, re
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DOCS = os.path.join(ROOT, ".tools/vendor/wow-ui-source/Interface/AddOns/Blizzard_APIDocumentationGenerated")
names = set()
files = glob.glob(os.path.join(DOCS, "Simple*APIDocumentation.lua")) + glob.glob(os.path.join(DOCS, "FrameAPI*Documentation.lua"))
for path in files:
    s = open(path, encoding="utf-8").read()
    fsec = re.search(r"Functions =\s*\{(.*?)\n\t\},\n\n\tEvents", s, re.S)
    if fsec:
        names.update(re.findall(r'\n\t\t\{\n\t\t\tName = "(\w+)",\n\t\t\tType = "Function"', fsec.group(1)))
out = ["-- GENERATED by scripts/gen-widget-methods.py from Blizzard_APIDocumentationGenerated (%d files). Do not edit." % len(files),
       "return {"]
for n in sorted(names):
    out.append('    %s = true,' % n)
out.append("}")
open(os.path.join(ROOT, "spec/fixtures/widget_methods.lua"), "w").write("\n".join(out) + "\n")
print("%d widget methods" % len(names))
